<?php if (!Mage::getSingleton('customer/session')->isLoggedIn()){?>
<div id="onepagecheckout_forgotbox" style="display: none;" class='customer_forgotpassword'>
    <div class="page-title">
        <span><?php echo $this->__('Forgot Password?') ?></span>
    </div>
    <?php
        $forgot_url	= $this->getUrl('*/load/forgotpassword', array('_secure'=>(!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS']==='on')));
        $http_mode	= (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS']==='on');
        if($http_mode)$forgot_url	= str_replace('http:', 'https:', $forgot_url);  
    ?>
    <div class="boxcontent form_fields">
        <p><?php echo $this->__('Please enter your email below and we will send you a new password.') ?></p>
		<div class='full field'>
			<label>
				<em>*</em><?php echo $this->__('Email') ?>
			</label>
			
			<div class="input-box">
				<input type="text" name="email" alt="email" id="email_address" class="input-text required-entry validate-email" value="<?php echo $this->htmlEscape($this->getEmailValue()) ?>" />
			</div>
        </div>
    </div>
    <div class="buttons-set">
        <p class="back-link"><a href="javascript:void(0);" class="onepagecheckout_loginlink"><small>&laquo; </small><?php echo $this->__('Back to Login') ?></a></p>
        <button type="submit" title="<?php echo $this->__('Submit') ?>" id="btn-forgot" class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button>
    </div>
    <script type="text/javascript">
    jQuery(document).ready(function($) {
        $('#btn-forgot').click(function(){
            data = $('#email_address').val();
            if(typeof ajax_request !== 'undefined')
            ajax_request.abort();
            ajax_request = $.ajax({
            	type: "POST",
            	url: "<?php echo $forgot_url;?>",
            	data: 'email='+data,
            	cache: false,
                beforeSend:  function() {
                    $('.load_forgot_pass').show();
                    $('.reg_log').hide();
                },
                success: function(html){
                    $('.load_forgot_pass').hide();
                    $('.reg_log').show();
                    var _json=$.parseJSON(html); 
                    if(_json.success == true){
                        alert(_json.message);
                    }else{
                        alert(_json.error);
                    }
                }
            });
        });
    });
    </script>
</div>
<?php }?>