<div class="ma-body-wrapper">
	<div class="container">
		<div class="body-wrapper">
			<div class="row">
				<div class="col-md-12 col-sm-12">
					<?php  echo $this->getLayout()->createBlock('banner7/banner7')->setTemplate('magentothem/banner7/banner7.phtml')->toHtml(); ?>
				</div>
<!--				<div class="col-md-4 col-sm-12">
					<?php // echo $this->getLayout()->createBlock('cms/block')->setBlockId('banner_home1')->toHtml() ?>
				</div>-->
			</div>
		</div>
	</div>
</div>