<?php
    $suvery = trim(Mage::getStoreConfig('onepagecheckout/suvery/enabled'));
    $suvery_question = Mage::getStoreConfig('onepagecheckout/suvery/question');
    $enable_orther_value_suvery = Mage::getStoreConfig('onepagecheckout/suvery/enable_other');
    if($suvery){
    $selectedsuveryFields = $this->getRequest()->getPost('onestepcheckout-feedback', false);
    $suveryValues = unserialize(Mage::getStoreConfig('onepagecheckout/suvery/values'));
?>
    <div class="suvery">
        <label for="id_suvery"><?php echo $this->__($suvery_question); ?></label><br />
        <select style="" name="suvery" id="id_suvery">
            <option value=""><?php echo $this->__('Please choose'); ?></option>
            <?php foreach($suveryValues as $value => $label):?>
                <option value="<?php echo  $label['value']?>" <?php echo $selected;?>><?php echo $label['value']?></option>
            <?php endforeach; ?>
            <?php if($enable_orther_value_suvery){ ?>
                <option value="other">Other</option>
            <?php } ?>
        </select>
        <div class="suvery_other">
            <label for="suvery_other"><?php echo $this->__('Please specity') ?></label><br />
            <textarea id="suvery_other" name="suvery_other" rows="4" style="width: 100%;"></textarea>
        </div>
    </div>
    <script type="text/javascript">
        jQuery(document).ready(function($) {
            $('#id_suvery').change(function(){
                if($(this).val() == 'other')
                {
                    $('.suvery_other').show();
                }else{
                    $('.suvery_other').hide();
                }
            });
        });
    </script>
<?php } ?>