<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>
<?php
/* Count for timer calculation declared here */
$count = 1;
$_productCollection=$this->getLoadedProductCollection();
$_helper = $this->helper('catalog/output');

/* Admin Controllers for timer are declared here */
$timer_active = Mage::getStoreConfig('timer/general/activate_magentothem_timer');
$timer_head_active = Mage::getStoreConfig('timer/general/activate_magentothem_heading');
$timer_desc_active = Mage::getStoreConfig('timer/general/activate_magentothem_description');
$timer_color = Mage::getStoreConfig('timer/magentothem_timer_color/text');
$desc_color = Mage::getStoreConfig('timer/magentothem_timer_color/description');
$head_color = Mage::getStoreConfig('timer/magentothem_timer_color/heading_text_color');
$timer_head = Mage::getStoreConfig('timer/general/heading');
$store = Mage::app()->getStore()->getCode();

$auto = $this->getConfig('auto');
$itemsDesktop = $this->getConfig('itemsDesktop');
$itemsDesktopSmall = $this->getConfig('itemsDesktopSmall');
$itemsTablet = $this->getConfig('itemsTablet');
$itemsMobile = $this->getConfig('itemsMobile');
$next_back = $this->getConfig('next_back');
$nav_ctrl = $this->getConfig('nav_ctrl');
$speed = $this->getConfig('speed');
?>

<script type="text/javascript">
	var j_blog = 1;
</script>
<?php if($this->getConfig('enabled')){ // start enable module?>
	<?php $this->getProducts() ?>
	<?php $_productCollection=$this->getProductCollection() ?>
	<div class="ma-timer-container">
		<?php				
			if ( !$this->getConfig('width_thumbnail') ){
				$w_thumbnail = 135;
			} else {
				$w_thumbnail = $this->getConfig('width_thumbnail');
			}
			if( !$this->getConfig('height_thumbnail') ){
				$h_thumbnail = 135;
			 }
			else {
				$h_thumbnail = $this->getConfig('height_thumbnail');
			}
		?>
		<?php if($this->getConfig('title')){?>
			<div class="ma-timer-title ma-title"><h2><?php echo $this->getConfig('title')?></h2></div>
		<?php }?>
		<?php if(!$_productCollection->count()): ?> 
			<div class="ma-timer">	
				<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
			</div>
		<?php else: ?>
			<?php
			$rows = $this->getConfig('row_show');
			?>
			<div class="row">
				<ul class="owl owl-times">
					<?php $_collectionSize = $_productCollection->count() ?>
					<?php $i=0; foreach ($_productCollection as $_product): ?>
					<?php $toDate = $_product->getSpecialTODate();?>
					<?php $fromDate = $_product->getSpecialFromDate(); ?>
					<?php if($i %$rows == 0) echo "<li class='timer-item'>"; ?>
						<div class="item-inner">
							<div class="ma-box-content">
								<?php
								$newFromDate = $_product->getNewsFromDate();
								$newToDate = $_product->getNewsToDate();                 
								$now = date("Y-m-d H:m(worry)");
								// Get the Special Price
								$specialprice = $_product->getSpecialPrice(); 
								// Get the Special Price FROM date
								$specialPriceFromDate = $_product->getSpecialFromDate();
								// Get the Special Price TO date
								$specialPriceToDate = $_product->getSpecialToDate();
								// Get Current date
								if(($specialprice&&($specialPriceFromDate <= $now && $specialPriceToDate >= $now)&& Mage::getStoreConfig('themeoptions/themeoptions_config/sale_label'))){
									$_savePercent = 100 - round(($_product->getSpecialPrice() / $_product->getPrice())*100);
									
									echo "<span class='hot-sale'>-".$_savePercent."%<small>Off</small></span>";
									//echo $now.' -- '.$newsFrom.' -- '.$newsTo;
								  }
								?>
								<div class="products clearfix">
									 <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
									  <span class="product-image">
									   <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($w_thumbnail,$h_thumbnail); ?>" width="$w_thumbnail" height="$h_thumbnail" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
									  </span>
									  <span class="product-image image-rotator">
									   <?php 
									   $product = $_product;
									   if ($product->getRotatorImage() && $product->getRotatorImage() !='no_selection') {
										//$imageTooltipResize = $this->getResizedUrl($imagetTooltip,600,400);
										$image = Mage::helper('catalog/image')->init($product, 'rotator_image')->resize($w_thumbnail, $h_thumbnail);
									   } else {
										$image = Mage::helper('catalog/image')->init($_product, 'small_image')->resize($w_thumbnail, $h_thumbnail);
									   }
									   ?>
									   <img src="<?php echo $image ?>" width="$w_thumbnail" height="$h_thumbnail" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
									   </span>   
									</a>
								</div>
								<div class="box-timer">
									<?php if($timer_active == 1) :?>
									<?php if(($_product->getPrice() > $_product->getSpecialPrice() || $_product->getTypeID() == 'bundle') && $_product->getTimershow() == 1) : ?>
									<?php if($_product->getSpecialPrice()!= 0 || $_product->getSpecialPrice()!= "" ) :?>
									<?php if($timer_head_active == 'showall' || $timer_head_active == 'listpage' && $timer_head_active!='hideall' && $timer_head!= '') : ?>
										<div id="heading<?php echo $count; ?>"><?php echo $timer_head ?></div>
									<?php endif; ?>
										<div class="countbox_<?php echo $count; ?> timer-grid clearfix"></div>
									<?php if($timer_desc_active == 'showall' || $timer_desc_active == 'listpage' && $timer_desc_active!='hideall') : ?>
															
										<?php
										if($_product->getTypeID() == 'bundle')
										{
											echo '<br/><h1 style="color:red">Discount up to '.(100 - $_product->getSpecialPrice()*1).'% </h1>';
										}
										?>
										<?php $count = $count + 1; ?>
									<?php endif;endif;endif;endif; ?>
								</div>
								<!--Condition for Timer Controllers goes here-->
								
								<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo $this->htmlEscape($_product->getName()) ?></a></h2>
								<?php if($this->getConfig('review')) echo $this->getReviewsSummaryHtml($_product, 'short') ?>
								<div class="price-box">
									<?php
									$sym = Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol(); 
									$price = $_product->getPrice();
									$specialprice = $_product->getFinalPrice();
									if($price != $specialprice){
									if($price != ''){
									echo '<p class="old-price"><span class="price-label">';
									echo $this->__('Regular Price'). ': </span>';
									echo '<span class="price">'.$sym.''.number_format($price,2).'</span></p>';
									}
									if($specialprice != '')
									{
									echo '<p class="special-price">
									<span class="price-label">Special Price</span>
									<span class="price">'.$sym.''.number_format($specialprice,2).'</span>
									</p> ';
									} 
									}else {
									echo '<div class="price-boxs">
									<span class="regular-price">
									<span class="price">'.$sym.''.number_format($price,2).'</span>                                    
									</span>    
									</div>';    
									}
									?>
								</div>
								<div class="actions">
									<?php if ($this->getConfig('addtocart')) { ?>
										<?php if($_product->isSaleable()): ?>
											<button type="button" title="<?php //echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><i class="fa fa-shopping-cart"></i><?php echo $this->__('Add to Cart') ?></span></button>
										<?php else: ?>
											<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
										<?php endif; ?>
									<?php }?>
									<?php if( $this->getConfig('addtowishlist') || $this->getConfig('addtocompare') || $this->getConfig('review') ){?>
										<ul class="add-to-links">
											<?php if( $this->getConfig('addtowishlist')): ?>
												<?php if ($this->helper('wishlist')->isAllow()) : ?>
													<li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist fa fa-heart"><em><?php echo $this->__('Add to Wishlist') ?></em></a></li>
												<?php endif; ?>
											<?php endif; ?>
											<?php if( $this->getConfig('addtocompare')): ?>
												<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
													<li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare fa fa-signal"><em><?php echo $this->__('Add to Compare') ?></em></a></li>
												<?php endif; ?>
											<?php endif; ?>
										
										</ul>
									<?php }?>
								</div>
								<?php if( $this->getConfig('description')){?>
									<div class="ma-desc">
										<?php if(!$this->getConfig('maxlength')){?>
											<?php echo nl2br($this->htmlEscape($_product->getShortDescription())) ?>
										<?php } else {?>
											<?php echo nl2br($this->cut_string_timer($this->htmlEscape($_product->getShortDescription()),$this->getConfig('maxlength'))) ?>			            
										<?php }?>			                    
									</div>
								<?php }?>
							</div>
						</div>
						<?php $i++; ?>
						<?php if($i %$rows == 0) echo "</li>"; ?>  
						<?php if($_collectionSize == $i && $i % $rows != 0) echo "</li>"; ?>
					<?php endforeach; ?>		
				</ul>
			</div>	
				<?php $count = 1; ?>
				<?php $_collectionSize = $_productCollection->count() ?>
					<?php $i=0; foreach ($_productCollection as $_product): ?>
					<?php $toDate = $_product->getSpecialTODate();?>
					<?php $fromDate = $_product->getSpecialFromDate(); ?>
					<!--Condition for Timer Controllers goes here-->
					<?php if($timer_active == 1) :?>
					<?php if(($_product->getPrice() > $_product->getSpecialPrice() || $_product->getTypeID() == 'bundle') && $_product->getTimershow() == 1) : ?>
					<?php if($_product->getSpecialPrice()!= 0 || $_product->getSpecialPrice()!= "" ) :?>
						<?php $_current_timer = time(); ?>
							<script type="text/javascript">
								var dthen<?php echo $count; ?> = new Date("<?php echo Date("m/d/y", strtotime($toDate)).' 11:59:00 PM'; ?>");
								start = "<?php echo Date("m/d/y h:i:s A", $_current_timer); ?>";
								start_date = Date.parse(start);
								var dnow<?php echo $count; ?> = new Date(start_date);
								if(CountStepper>0)
									ddiff= new Date((dnow<?php echo $count; ?>)-(dthen<?php echo $count; ?>));
								else
									ddiff = new Date((dthen<?php echo $count; ?>)-(dnow<?php echo $count; ?>));
								//gsecs<?php echo $count; ?> = Math.floor(ddiff.valueOf()/1000);
								<?php if(strtotime($fromDate) <= $_current_timer){ ?>
									gsecs<?php echo $count; ?> = Math.floor(ddiff.valueOf()/1000);
								<?php }else{ ?>
									gsecs<?php echo $count; ?> = -1;
								<?php } ?>

								var iid<?php echo $count; ?> = "countbox_<?php echo $count; ?>";
								CountBack_slider(gsecs<?php echo $count; ?>,"countbox_<?php echo $count; ?>", <?php echo $count; ?>);
								j_blog++;
							</script>
					<?php $count = $count + 1; ?>
					<?php endif;endif;endif; ?>
					<!-- -->
					<?php $i++; ?>
					<?php endforeach; ?>

                <script type="text/javascript">					
					$jq(document).ready(function(){
					    $jq(".ma-timer-container .owl").owlCarousel({
							autoPlay : <?php if($auto) echo 'true'; else echo 'false'; ?>,
							items : <?php if($itemsDesktop) echo $itemsDesktop; else echo '5'; ?>,
							itemsDesktop : [1199,<?php if($itemsDesktop) echo $itemsDesktop; else echo '5'; ?>],
							itemsDesktopSmall : [980,<?php if($itemsDesktopSmall) echo $itemsDesktopSmall; else echo '3'; ?>],
							itemsTablet: [768,<?php if($itemsTablet) echo $itemsTablet; else echo '2'; ?>],
							itemsMobile : [479,<?php if($itemsMobile) echo $itemsMobile; else echo '1'; ?>],
							slideSpeed : <?php if($speed) echo $speed; else echo '500'; ?>,
							paginationSpeed : <?php if($speed) echo $speed; else echo '500'; ?>,
							rewindSpeed : <?php if($speed) echo $speed; else echo '500'; ?>,
							navigation : <?php if($next_back) echo 'true'; else echo 'false'; ?>,
							stopOnHover : true,
							pagination : <?php if($nav_ctrl) echo 'true'; else echo 'false'; ?>,
							scrollPerPage:true,
						});
					});
				</script>
		<?php endif; ?> 
	</div> 
<?php } ?>