<?php
/**
 * zeonsolutions inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.zeonsolutions.com/shop/license-community.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * This package designed for Magento Community edition
 * =================================================================
 * zeonsolutions does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * zeonsolutions does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   design
 * @package    base_default
 * @version    0.0.1
 * @copyright  @copyright Copyright (c) 2013 zeonsolutions.Inc. (http://www.zeonsolutions.com)
 * @license    http://www.zeonsolutions.com/shop/license-community.txt
 */
?>
<?php $_manufacturer = $this->getManufacturer(); ?>
<?php $_helper = $this->helper('catalog/output'); ?>
<?php $processor = Mage::helper('zeon_manufacturer')->getBlockTemplateProcessor(); ?>
<div class="page-head">
    <h3><?php echo Mage::getModel('zeon_manufacturer/manufacturer')->getManufacturerName($_manufacturer->getManufacturer(), Mage::app()->getStore()->getId()) ?></h3>
</div>
<div class="category-view">
    <div class="clearfix" style="margin-bottom: 1px";>
        <p class="category-image">
            <?php if ($_manufacturer->getManufacturerBanner()): ?>
                <a href="#"><img alt="<?php echo $_manufacturer->getManufacturerBanner() ?>" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'manufacturer' . '/' . $_manufacturer->getManufacturerBanner() ?>" height="300" width="700"></a> 
            <?php endif; ?>
        </p>
        <div id="manufacturer-description" class="category-description">
            <div class="right" >
                <a href="<?php echo $this->getCurrentUrl() ?>"><img alt="<?php echo $_manufacturer->getManufacturerLogo() ?>" title="<?php echo $_manufacturer->getManufacturerLogo() ?>" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'manufacturer' . '/' . $_manufacturer->getManufacturerLogo() ?>" width="100" height="100"></a>
            </div>
            <?php echo $processor->filter($_manufacturer->getDescription()); ?>

        </div>

    </div>
    <?php echo $this->getToolbarHtml() ?>
    <div class="category-products">
        <?php if (($_products = $this->getProductCollection()) && $_collectionSize = $_products->getSize()): ?>

            <?php if ($this->getMode() != 'grid'): ?>

                <?php $_iterator = 0; ?>
                <ol class="products-list" id="products-list">
                    <?php foreach ($_products->getItems() as $_product): ?>
                        <li class="item<?php if (++$_iterator == sizeof($_products->getItems())): ?> last<?php endif; ?>">
                        <div class="item-inner">
                            <div class="row">
                                <div class=" products-images col-sm-4 col-md-4 col-sms-12 ">
                                    <div class="products clearfix">
                                        <?php // Product Image ?>
                                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(300, 400); ?>" width="300" height="400" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                                        <?php // Product description ?>	
                                    </div>	
                                </div>
                                <div class="product-shop col-sm-8 col-md-8 col-sms-12 ">
                                    <div class="f-fix">
                                        <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                                        <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?></a></h2>
                                        <?php if ($_product->getRatingSummary()): ?>
                                            <?php echo $this->getReviewsSummaryHtml($_product) ?>
                                        <?php else: ?>
                                            <p class="no-ratings"></p>
                                        <?php endif; ?>

                                        <?php echo $this->getPriceHtml($_product, true) ?>
                                        <div class="desc std">
                                            <?php $descr = $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description'); ?>
                                            <?php echo substr($descr, 1, 300); ?>
                                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
                                        </div>

                                        <div class="ma-box-content">
                                            <div class="actions">
                                                <?php if ($_product->isSaleable()): ?>
                                                    <button type="button" title="<?php //echo $this->__('Add to Cart')      ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><i class="fa fa-shopping-cart"></i><?php echo $this->__('Add to Cart') ?></span></button>
                                                <?php else: ?>
                                                    <p class="availability out-of-stock"><a class="contact" href="<?php echo Mage::getUrl("contacts") ?>"><?php echo $this->__('Contact Us'); ?></a></p>
                                                    <!--<span><?php // echo $this->__('Out of stock') ?></span>--> 
                                                <?php endif; ?>
                                                <ul class="add-to-links">
                                                    <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                                        <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" title="<?php //echo $this->__('Add to Wishlist')      ?>" class="link-wishlist fa fa-heart"><em><?php echo $this->__('Add to Wishlist') ?></em></a></li>
                                                    <?php endif; ?>
                                                    <?php if ($_compareUrl = $this->getAddToCompareUrl($_product)): ?>
                                                        <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" title="<?php //echo $this->__('Add to Compare')      ?>" class="link-compare fa fa-signal"><em><?php echo $this->__('Add to Compare') ?></em></a></li>
                                                    <?php endif; ?>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>	
                                </div>
                            </div>
                        </div>
                    </li>
                    <?php endforeach; ?>
                </ol>

            <?php else: ?>

                <?php $_columnCount = $this->getColumnCount();?>
                <?php
                $i = 0;
                foreach ($_products->getItems() as $_product):
                    ?>
                    <?php if ($i++ % $_columnCount == 0): ?>
                    <ul class="products-grid row">
                    <?php endif ?> 
                    <li class="col-sm-3 col-md-3 col-sms-12 col-smb-12 item<?php if (($i - 1) % $_columnCount == 0): ?> first<?php elseif ($i % $_columnCount == 0): ?> last<?php endif; ?>">
                        <div class="item-inner">
                            <div class="ma-box-content">
                                <?php
                                $newFromDate = $_product->getNewsFromDate();
                                $newToDate = $_product->getNewsToDate();
                                $now = date("Y-m-d H:m(worry)");
                                // Get the Special Price
                                $specialprice = $_product->getSpecialPrice();
                                // Get the Special Price FROM date
                                $specialPriceFromDate = $_product->getSpecialFromDate();
                                // Get the Special Price TO date
                                $specialPriceToDate = $_product->getSpecialToDate();
                                // Get Current date
                                if ($specialprice && (($specialPriceFromDate <= $now && $specialPriceToDate >= $now) || (($specialPriceFromDate <= $now && $specialPriceFromDate != NULL) && $specialPriceToDate == '')) && Mage::getStoreConfig('themeoptions/themeoptions_config/sale_label')) {
                                    $_savePercent = 100 - round(($_product->getSpecialPrice() / $_product->getPrice()) * 100);
                                    echo "<span class='hot-sale'>-" . $_savePercent . "%<small>Off</small></span>";
                                } else {
                                    if ((($newFromDate <= $now && $newToDate >= $now) || (($newFromDate <= $now && $newFromDate != NULL) && $newToDate == NULL)) && Mage::getStoreConfig('themeoptions/themeoptions_config/new_label')) {
                                        ?>
                                        <div class="label-pro-new"><span><?php echo $this->__('new') ?></span></div>
                                        <?php
                                    }
                                }
                                ?>
                                <div class="products">
                                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                                        <span class="product-image">
                                            <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(300, 400); ?>" width="300" height="400" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                                        </span>
                                        <span class="product-image image-rotator">
                                            <?php
                                            $product = Mage::getModel('catalog/product')->load($_product->getId());
                                            if ($product->getRotatorImage() && $product->getRotatorImage() != 'no_selection') {
                                                //$imageTooltipResize = $this->getResizedUrl($imagetTooltip,600,400);
                                                $image = Mage::helper('catalog/image')->init($product, 'rotator_image')->resize(300, 400);
                                            } else {
                                                $image = Mage::helper('catalog/image')->init($_product, 'small_image')->resize(300, 400);
                                            }
                                            ?>
                                            <img src="<?php echo $image ?>" width="300" height="400" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                                        </span>   
                                    </a>

                                </div>
                                <h2 class="product-name">
                                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                                <?php if ($_product->getRatingSummary()): ?>
                                    <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                                <?php else: ?>
                                    <p class="no-ratings"></p>
                                <?php endif; ?>
                                <?php echo $this->getPriceHtml($_product, true) ?>
                                <div class="actions">
                                    <?php if ($_product->isSaleable()): ?>
                                        <button type="button" title="<?php //echo $this->__('Add to Cart')   ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><i class="fa fa-shopping-cart"></i><?php echo $this->__('Add to Cart') ?></span></button>
                                    
                                    <?php elseif($_product->getPreorder()): ?>
                                        <button class="button btn-cart">
                                            <span>
                                                <a style="color: white;" class="contact" href="<?php echo Mage::getUrl("contacts") ?>?product_title=<?php echo $_product->getName(); ?>">
                                                    <?php echo $this->__('Pre-order'); ?>
                                                </a>
                                            </span>
                                        </button>
                                    <?php else: ?>
                                        <p class="availability out-of-stock"><a class="contact" href="<?php echo Mage::getUrl("contacts") ?>"><?php echo $this->__('Contact Us'); ?></a></p>
                                        <!--<span><?php // echo $this->__('Out of stock') ?></span>--> 
                                    <?php endif; ?>
                                    <ul class="add-to-links">
                                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                            <li class="last"><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" title="<?php //echo $this->__('Add to Wishlist')   ?>" class="link-wishlist fa fa-heart"><em><?php echo $this->__('Add to Wishlist') ?></em></a></li>
                                        <?php endif; ?>
                                        <?php if ($_compareUrl = $this->getAddToCompareUrl($_product)): ?>
                                            <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" title="<?php //echo $this->__('Add to Compare')   ?>" class="link-compare fa fa-signal"><em><?php echo $this->__('Add to Compare') ?></em></a></li>
                                        <?php endif; ?>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </li>
                    <?php if ($i % $_columnCount == 0 || $i == $_collectionSize): ?>
                    </ul>
                <?php endif ?>
                <?php endforeach ?>
            <?php endif; ?>
        <?php endif; ?>
    </div>
    <?php echo $this->getToolbarHtml() ?>
</div>