<?php if (!($_shippingRateGroups = $this->getShippingRates())): ?>
    <strong><?php echo $this->__('Sorry, no quotes are available for this order at this time.') ?></strong>
<?php else: ?>
    <?php if (count($_shippingRateGroups)=='1' && Mage::getStoreConfig('onepagecheckout/general/hide_shipping_method')):?>
        <dl class="shipment-methods" style="display: none">
            <?php foreach ($_shippingRateGroups as $code => $_rates): ?>
            <dd><?php echo $this->getCarrierName($code) ?></dd>
                <?php foreach ($_rates as $_rate): ?>
                <dt>
                   <?php if ($_rate->getErrorMessage()): ?>
                   <ul class="messages"><li class="error-msg"><ul><li><?php echo $_rate->getErrorMessage() ?></li></ul></li></ul>
                   <?php else: ?>
                   <input name="shipping_method" type="radio" value="<?php echo $_rate->getCode() ?>" class="radio" id="s_method_<?php echo $_rate->getCode() ?>" checked="checked" />
                   <label for="s_method_<?php echo $_rate->getCode() ?>"><!--<b><?php echo $this->getCarrierName($code) ?>:</b>--> <?php echo $_rate->getMethodTitle() ?>
                        <strong>
                        <?php $_excl = $this->getShippingPrice($_rate->getPrice(), $this->helper('tax')->displayShippingPriceIncludingTax()); ?>
                        <?php $_incl = $this->getShippingPrice($_rate->getPrice(), true); ?>
                        <?php echo $_excl; ?>
                        <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                            (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
                        <?php endif; ?>
                        </strong>
                    </label>
                   <?php endif ?>
                   </dt>
                <?php endforeach; ?>
            <?php endforeach; ?>
        </dl>
    <?php else: ?>
        <dl class="shipment-methods">
            <?php foreach ($_shippingRateGroups as $code => $_rates): ?>
                        <dd><?php echo $this->getCarrierName($code) ?></dd>
                    <?php foreach ($_rates as $_rate): ?>
                        <dt>

                           <?php if ($_rate->getErrorMessage()): ?>
                            <ul class="messages"><li class="error-msg"><ul><li><?php echo $_rate->getErrorMessage() ?></li></ul></li></ul>
                           <?php else: ?>
                                <input name="shipping_method" type="radio" class="validate-one-required-by-name radio" value="<?php echo $_rate->getCode() ?>" id="s_method_<?php echo $_rate->getCode() ?>"<?php if($_rate->getCode()===$this->getAddressShippingMethod()) echo ' checked="checked"' ?> />
                                <label for="s_method_<?php echo $_rate->getCode() ?>"><!--<b><?php echo $this->getCarrierName($code) ?>:</b>--> <?php echo $_rate->getMethodTitle() ?>
                                <strong>
                                <?php $_excl = $this->getShippingPrice($_rate->getPrice(), $this->helper('tax')->displayShippingPriceIncludingTax()); ?>
                                <?php $_incl = $this->getShippingPrice($_rate->getPrice(), true); ?>

                                <?php echo $_excl; ?>
                                <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                                    (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
                                <?php endif; ?>
                                </strong>
                                </label>
                           <?php endif ?>
                        </dt>
                    <?php endforeach; ?>
            <?php endforeach; ?>
        </dl>
    <?php endif; ?>
<?php endif; ?>
<script type="text/javascript">
    jQuery(document).ready(function($) {
        $('input[name=shipping_method]').click(function(){
            payment_method = $("input[name='payment[method]']:checked").val();
            shipping_method = $("input[name='shipping_method']:checked").val();
            data = 'payment_method='+payment_method+'&shipping_method='+shipping_method;
            url = $('#mst-address-request').val()+'load/update_shipping_payment';
            if(typeof ajax_request !== 'undefined')
            ajax_request.abort();
            ajax_request = $.ajax({
            	type: "POST",
            	url: url,
            	data: data,
            	cache: false,
                beforeSend:  function() {
                    $('.load_review').show();
                    $('.load_payment').show();
                    $('.opc_tool-tip_methods').css('opacity','0.5');
                    $('#checkout-review-table-wrapper').css('opacity','0.5');
                },
                success: function(html){
                    var _json=$.parseJSON(html); 
                    $('.loading_image').hide();
                    $('.opc_available_additional').css('opacity','1');
                    $('.opc_tool-tip_methods').css('opacity','1');
                    $('#checkout-review-table-wrapper').css('opacity','1');
                    $('#checkout-review-table-wrapper #shopping-cart-totals-table').remove();
                    $('#checkout-review-load').html(_json.info);
                    $('#checkout-shipping-method-load').html(_json.shipping_method);                        
                    $('#checkout-payment-method-load').html(_json.payment_method);
                    if(_json.validate_cart == 0){
                        location.reload();
                    }
                }
            });
        });
    });
</script>