<?php if( $this->getConfig('enabled')){ // start enable module ?>
<?php if(count($this->getItems())): ?>
    <?php
		$title = $this->getConfig('title');
        $auto = $this->getConfig('auto');
		$speed = $this->getConfig('speed');
		$show_price = $this->getConfig('show_price');
        $review = $this->getConfig('review');
		$itemsDefault = $this->getConfig('itemsDefault');
		$itemsDesktop = $this->getConfig('itemsDesktop');
		$itemsDesktopSmall = $this->getConfig('itemsDesktopSmall');
		$itemsTablet = $this->getConfig('itemsTablet');
		$itemsMobile = $this->getConfig('itemsMobile');
        $width_thumbnail = $this->getConfig('width_thumbnail');
        $height_thumbnail = $this->getConfig('height_thumbnail');
        $nav_ctrl = $this->getConfig('nav_ctrl');
        $next_back = $this->getConfig('next_back');	
    ?>
    <div class="ma-relatedslider-container">
		<?php if($title){?>
			<div class="ma-relatedslider-title ma-title"><h2><?php echo $this->__($title) ?></h2></div>
		<?php }?>
		<!--<div class="row">-->
			<ul class="owl related">
				<?php
				$rows = $this->getConfig('row_show');
				$rowi = 0;
                                $counter = 0;
                                $itens = array();
                                
                                 foreach ($this->getItems() as $item):
                                     $itens[] = $item;  
                                 endforeach;
				?>
				<?php // $this->setColumnCount(5); // uncomment this line if you want to have another number of columns. also can be changed in layout ?>
				<?php // $this->resetItemsIterator() ?>
				<?php for($_i=0;$_i<$this->getRowCount();$_i++): ?>
					<?php for($_j=0;$_j<$this->getColumnCount();$_j++): ?>
						<?php if($_link = $itens[$counter]):?>
						<?php if($rowi % $rows == 0) echo "<li class='upsell-item'>"; ?>
							<div class="item-inner">
								<a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_link->getName()) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_link, 'small_image')->resize($width_thumbnail, $height_thumbnail) ?>" alt="<?php echo $this->htmlEscape($_link->getName()) ?>" /></a>
								<?php if( $review ): ?>
									<?php echo $this->getReviewsSummaryHtml($_link) ?>
								<?php endif; ?>
								<h3 class="product-name"><a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_link->getName()) ?>"><?php echo $this->htmlEscape($_link->getName()) ?></a></h3>
								<?php if( $show_price ): ?>
									<?php echo $this->getPriceHtml($_link, true, '-related') ?>
								<?php endif; ?>
							</div>
						<?php $rowi++;?>
							<?php if($rowi % $rows == 0) echo "</li>"; ?>   
						<?php endif; ?>
                                            <?php $counter++; ?>
					<?php endfor; ?>
				<?php endfor; ?>
				<?php if($rowi % $rows != 0) echo "</li>"; ?>
			</ul>
		<!--</div>-->
    </div>
	<script type="text/javascript">
		$jq(document).ready(function(){
			$jq(".ma-relatedslider-container .owl.related").owlCarousel({
				autoPlay : <?php if($auto) echo 'true'; else echo 'false'; ?>,
				items : <?php if($itemsDefault) echo $itemsDefault; else echo '6'; ?>,
				itemsDesktop : [1199,<?php if($itemsDesktop) echo $itemsDesktop; else echo '5'; ?>],
				itemsDesktopSmall : [980,<?php if($itemsDesktopSmall) echo $itemsDesktopSmall; else echo '3'; ?>],
				itemsTablet: [768,<?php if($itemsTablet) echo $itemsTablet; else echo '2'; ?>],
				itemsMobile : [479,<?php if($itemsMobile) echo $itemsMobile; else echo '1'; ?>],
				slideSpeed : <?php if($speed) echo $speed; else echo '500'; ?>,
				paginationSpeed : <?php if($speed) echo $speed; else echo '500'; ?>,
				rewindSpeed : <?php if($speed) echo $speed; else echo '500'; ?>,
				navigation : <?php if($next_back) echo 'true'; else echo 'false'; ?>,
				stopOnHover : true,
				pagination : <?php if($nav_ctrl) echo 'true'; else echo 'false'; ?>,
				scrollPerPage:true,
			});
		});
	</script>
<?php endif ?>
<?php } ?>