<div class="body-bottom-wrapper">
	<div class="container">
		<?php  echo $this->getLayout()->createBlock('lastestproduct/lastestproduct')->setTemplate('magentothem/lastestproduct/lastestproduct.phtml')->toHtml(); ?>
		
		<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('box_newsletter')->toHtml() ?>
		
		<?php  echo $this->getLayout()->createBlock('blog/menu_sidebar')->setTemplate('magentothem_blog/blog_slide.phtml')->toHtml(); ?>

	</div>	
</div>