<?php
$enabled_slide = Mage::getStoreConfig('blog/slide/enabled');
if($enabled_slide){
$numberrow = $this->getConfig('numberrow');
$speed = $this->getConfig('speed');
$auto = $this->getConfig('auto');
$itemsDesktop = $this->getConfig('itemsDesktop');
$itemsDesktopSmall = $this->getConfig('itemsDesktopSmall');
$itemsTablet = $this->getConfig('itemsTablet');
$itemsMobile = $this->getConfig('itemsMobile');
$show_image = $this->getConfig('showimage');
$show_title = $this->getConfig('showtitle');
$show_author = $this->getConfig('showauthor');
$show_time = $this->getConfig('showtime');
$show_shortcontent = $this->getConfig('showshortcontent');
$show_readmore = $this->getConfig('showreadmore');
$next_back = $this->getConfig('next_back');
$nav_ctrl = $this->getConfig('nav_ctrl');
?>
<?php if ($posts = $this->getRecent()):  $i = 0;?>
	<div class="menu-recent">
		<div class="blog-titles ma-title"><h2><?php echo $this->__('From The Blog') ?></h2></div>
		<div class="row">
			<ul class="owl">
				<?php foreach ($posts as $post): ?>
					<?php if($i % $numberrow == 0) echo '<li>'; ?>
						<div class="item-inner">
								<?php if($show_image) echo '<img alt="" src="'.Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA). $post->getThumbnailimage().'"/>'; ?>
							<div class="blog-content">
								<?php if($show_title): ?> <a href="<?php echo $post->getAddress(); ?>" ><?php echo '<span class="blog-title">'.$post->getTitle().'</span>' ?></a> <?php endif; ?>
								
								<?php if($show_shortcontent) echo '<p>' .strip_tags($this->getContentBlogSidebar($post->getShortContent(),125)) .'</p>';?>
								
								<?php $s = $post->getCreatedTime(); $date = strtotime($s); ?>
								<?php if($show_author) echo '<p class="author">By '.$post->getUser(); if($show_author && $show_time) echo ' - '; if($show_time) echo '<span class="date-time">' .date("d M Y", $date).' ( '.$this->getcountcomment($post->getPostId()) .' comments )</span> '; ?></p>
								
								<?php if($show_readmore): ?> <a class="readmore" href="<?php echo $post->getAddress(); ?>">Read more > </a> <?php endif; ?>
							</div>
						</div>
					<?php 
					$i++;
					if($i % $numberrow == 0)echo '</li>';  ?>
				<?php endforeach; ?>
				<?php if($i % $numberrow != 0)echo '</li>'; ?>
			</ul>
		</div>
	</div>
	 <script type="text/javascript">
		$jq(document).ready(function(){
			$jq(".menu-recent .owl").owlCarousel({
				autoPlay : <?php if($auto) echo 'true'; else echo 'false'; ?>,
				items : <?php if($itemsDesktop) echo $itemsDesktop; else echo '5'; ?>,
				itemsDesktop : [1199,<?php if($itemsDesktop) echo $itemsDesktop; else echo '5'; ?>],
				itemsDesktopSmall : [980,<?php if($itemsDesktopSmall) echo $itemsDesktopSmall; else echo '3'; ?>],
				itemsTablet: [768,<?php if($itemsTablet) echo $itemsTablet; else echo '2'; ?>],
				itemsMobile : [479,<?php if($itemsMobile) echo $itemsMobile; else echo '1'; ?>],
				slideSpeed : <?php if($speed) echo $speed; else echo '500'; ?>,
				paginationSpeed : <?php if($speed) echo $speed; else echo '500'; ?>,
				rewindSpeed : <?php if($speed) echo $speed; else echo '500'; ?>,
				navigation : <?php if($next_back) echo 'true'; else echo 'false'; ?>,
				stopOnHover : true,
				pagination : <?php if($nav_ctrl) echo 'true'; else echo 'false'; ?>,
				scrollPerPage:true,
			});
		});
	</script>
<?php endif;
}
?>
