<div class="ma-body-wrapper">
	<div class="container">
		<div class="body-wrapper">
			<div class="row">
				<div class="col-md-9 col-sm-12">
					<?php  echo $this->getLayout()->createBlock('banner7/banner7')->setTemplate('magentothem/banner7/banner7.phtml')->toHtml(); ?>
				</div>
				<div class="col-md-3 col-sm-12">
					<?php  echo $this->getLayout()->createBlock('timer/timer')->setTemplate('magentothem/timer/timer.phtml')->toHtml(); ?>
				</div>
			</div>
		</div>
	</div>
</div>