<?php /** @var $this Magentothem_Ajaxlogin_Block_Login */ ?>
<script type="text/javascript">


</script>

<div id="ajax-logout-block">
</div>
<div class="ajax-load-img">
    <img alt="" src="<?php echo $this->getAjaxLoadImage() ?>" />
</div>
<div class="ajax-body-logout">
    <div class="account-login">
        <div class="page-title">
            <h1></h1>
            <a href="javascript:void(0);" class="a-close-frm" onclick="closeLogoutForm()"><span>Close</span></a>
        </div>
        <div class="ajax-content">
            <h1></h1>
            <p class="error-msg"></p>
        </div>
    </div>
</div>
